export const tokenTypes = {
  id: { id: 0, name: "identificador", shortened: "id" },
  constanteEntero: { id: 1, name: "Entero", shortened: "int" },
  constanteReal: { id: 2, name: "Real", shortened: "float"},
  cadena: { id: 3, name: "Cadena", shortened: "string"},
  dataType: { id: 4, name: "Tipo de dato", shortened: "datatype"},  
  opSuma: { id: 5, name: "Operador Suma", shortened: "+" },
  "+": { id: 5, name: "Operador Suma", shortened: "+" },
  "-": { id: 5, name: "Operador Suma", shortened: "-"},
  opMultiplicacion: { id: 6, name: "Operador Multiplicacion", shortened: "*" },
  "*": { id: 6, name: "Operador Multiplicacion", shortened: "*"},
  "/": { id: 6, name: "Operador Multiplicacion", shortened: "/" },
  opRelacional: { id: 17, name: "Operador Relacional", shortened: "opRela" },
  "<": { id: 7, name: "Operador Relacional", shortened: "<" },
  ">": { id: 7, name: "Operador Relacional", shortened: ">" },
  "<=": { id: 7, name: "Operador Relacional", shortened: "<=" },
  ">=": { id: 7, name: "Operador Relacional", shortened: ">=" },
  opLogico: { id: 8, name: "Operador Logico", shortened: "oplog" },
  "||": { id: 8, name: "Operador OR", shortened: "||" },
  "&&": { id: 9, name: "Operador AND", shortened: "&&" },
  "!": { id: 10, name: "Operador Not", shortened: "!" },
  "!=": { id: 11, name: "Operador Igualdad", shortened: "!=" },
  "==": { id: 11, name: "Operador Igualdad", shortened: "==" },
  ";": { id: 12, name: "Punto y coma", shortened: ";" },
  ",": { id: 13, name: "Coma", shortened: "," },
  "(": { id: 14, name: "Parentesis Apertura", shortened: "(" },
  ")": { id: 15, name: "Parentesis Cierre", shortened: ")" },
  "{": { id: 16, name: "Llave Apertura", shortened: "{" },
  "}": { id: 17, name: "Llave cierre", shortened: "}" },
  "=": { id: 18, name: "Igual", shortened: "=" },
  if: { id: 19, name: "Condicional if", shortened: "if" },
  while: { id: 20, name: "Condicional while", shortened: "while" },
  return: { id: 21, name: "Palabra reserbada", shortened: "return" },
  else: { id: 22, name: "Condicional else", shortened: "else" },
  $: { id: 23, name: "Terminal", shortened: "$" },
};
export const keywords = ["if", "while", "return", "else", "constante"];
export const dataType = ["int", "float", "char", "void", "string"];
export const operators = [
  "||",
  "&&",
  "+",
  "-",
  "==",
  "<",
  ">",
  "<=",
  ">=",
  "!=",
  "*",
  "/",
  "|",
  "&",
  "!",
  "=",
];
export const punctuation = [";", ",", "(", ")", "{", "}"];
export const digits = /[0-9]/;
export const letters = /[a-zA-Z]/;