export const tokenTypes = {
  id: { id: 0, name: "identificador" },
  constanteEntero: { id: 1, name: "Entero" },
  constanteReal: { id: 2, name: "Real" },
  cadena: { id: 3, name: "Cadena" },
  dataType: { id: 4, name: "Tipo de dato" },
  opSuma: { id: 5, name: "Operador Suma" },
  "+": { id: 5, name: "Operador Suma" },
  "-": { id: 5, name: "Operador Suma" },
  opMultiplicacion: { id: 6, name: "Operador Multiplicacion" },
  "*": { id: 6, name: "Operador Multiplicacion" },
  "/": { id: 6, name: "Operador Multiplicacion" },
  opRelacional: { id: 17, name: "Operador Relacional" },
  "<": { id: 7, name: "Operador Relacional" },
  ">": { id: 7, name: "Operador Relacional" },
  "<=": { id: 7, name: "Operador Relacional" },
  ">=": { id: 7, name: "Operador Relacional" },
  opLogico: { id: 8, name: "Operador Logico" },
  "||": { id: 8, name: "Operador OR" },
  "&&": { id: 9, name: "Operador AND" },
  "!": { id: 10, name: "Operador Not" },
  "!=": { id: 11, name: "Operador Igualdad" },
  "==": { id: 11, name: "Operador Igualdad" },
  ";": { id: 12, name: "Punto y coma" },
  ",": { id: 13, name: "Coma" },
  "(": { id: 14, name: "Parentesis Apertura" },
  ")": { id: 15, name: "Parentesis Cierre" },
  "{": { id: 16, name: "Llave Apertura" },
  "}": { id: 17, name: "Llave cierre" },
  "=": { id: 18, name: "Igual" },
  if: { id: 19, name: "Condicional if" },
  while: { id: 20, name: "Condicional while" },
  return: { id: 21, name: "Palabra reserbada" },
  else: { id: 22, name: "Condicional else" },
  $: { id: 23, name: "Terminal" },
};
export const keywords = ["if", "while", "return", "else", "constante"];
export const dataType = ["int", "float", "char", "void", "string"];
export const operators = [
  "||",
  "&&",
  "+",
  "-",
  "==",
  "<",
  ">",
  "<=",
  ">=",
  "!=",
  "*",
  "/",
  "|",
  "&",
  "!",
  "=",
];
export const punctuation = [";", ",", "(", ")", "{", "}"];
export const digits = /[0-9]/;
export const letters = /[a-zA-Z]/;